source 'https://github.com/CocoaPods/Specs.git'

target 'MovingCircleMapView', :exclusive => true do
  pod "MovingCircleMapView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MovingCircleMapView", :path => "../"

  
end
